import { useEffect, useState } from 'react';
import { api } from '../api/client';

interface UploadItem {
  id: number;
  fileName: string;
  originalName: string;
  mimeType: string;
  fileSize: number;
  createdAt: string;
  imgbbUrl?: string;
  imgbbThumbnailUrl?: string;
}

interface GalleryItem {
  id: number;
  toolId: number;
  toolName: string;
  fileName: string;
  outputType: string;
  nodeId: string;
  createdAt: string;
  prompt?: string;
  sourceUploadUrl?: string;
}

type Tab = 'uploads' | 'gallery';

interface ImagePickerModalProps {
  open: boolean;
  onClose: () => void;
  onSelect: (item: { fileName: string; previewUrl: string; label: string }) => void;
  /** Optional: exclude gallery items generated by a specific tool (to avoid weird recursion) */
  excludeToolId?: number;
}

/**
 * Modal that lets the user pick an image from either their Uploads library
 * (images they have manually uploaded) or the Gallery (outputs of past runs).
 * Calls onSelect with the fileName (URL that RunningHub accepts) and a previewUrl.
 */
export default function ImagePickerModal({ open, onClose, onSelect, excludeToolId }: ImagePickerModalProps) {
  const [tab, setTab] = useState<Tab>('uploads');
  const [uploads, setUploads] = useState<UploadItem[] | null>(null);
  const [gallery, setGallery] = useState<GalleryItem[] | null>(null);
  const [loadingUploads, setLoadingUploads] = useState(false);
  const [loadingGallery, setLoadingGallery] = useState(false);
  const [error, setError] = useState('');
  const [search, setSearch] = useState('');

  useEffect(() => {
    if (!open) return;
    setError('');
    setSearch('');
    if (tab === 'uploads' && uploads === null) {
      setLoadingUploads(true);
      api.listUploads()
        .then(r => setUploads((r.uploads || []) as UploadItem[]))
        .catch(e => setError(e.message))
        .finally(() => setLoadingUploads(false));
    } else if (tab === 'gallery' && gallery === null) {
      setLoadingGallery(true);
      api.listGallery()
        .then(r => setGallery(r.items || []))
        .catch(e => setError(e.message))
        .finally(() => setLoadingGallery(false));
    }
  }, [open, tab, uploads, gallery]);

  if (!open) return null;

  const handlePickUpload = (u: UploadItem) => {
    // For uploads, fileName is the imgbb URL after the migration.
    // For very old records it might be a local path; in that case the proxy handles it.
    const fileName = u.imgbbUrl || u.fileName;
    const previewUrl = u.imgbbThumbnailUrl || u.imgbbUrl || `/api/uploads/${u.id}/file`;
    onSelect({ fileName, previewUrl, label: u.originalName });
  };

  const handlePickGallery = (g: GalleryItem) => {
    // fileName is the RESULT of the previous edit (imgbb URL).
    // sourceUploadUrl is the BEFORE image (input). We want the result.
    const fileName = g.fileName;
    // For preview, use the result URL directly (imgbb CDN is fast and public).
    // Fallback to the proxy if fileName is not an http URL (legacy records).
    const previewUrl = g.fileName?.startsWith('http')
      ? g.fileName
      : `/api/gallery/files/${g.id}`;
    const label = g.toolName + (g.prompt ? ` — ${g.prompt.slice(0, 40)}` : '') + ' (result)';
    onSelect({ fileName, previewUrl, label });
  };

  const filteredUploads = uploads?.filter(u => {
    if (!search.trim()) return true;
    return u.originalName.toLowerCase().includes(search.toLowerCase());
  });
  const filteredGallery = gallery
    ?.filter(g => !excludeToolId || g.toolId !== excludeToolId)
    .filter(g => {
      if (!search.trim()) return true;
      const hay = `${g.toolName} ${g.prompt || ''}`.toLowerCase();
      return hay.includes(search.toLowerCase());
    });

  return (
    <div className="overlay" onClick={onClose}>
      <div
        className="card"
        style={{
          width: 'min(95vw, 960px)',
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column' as const,
          gap: 12,
          padding: 20,
        }}
        onClick={e => e.stopPropagation()}
      >
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <h3 style={{ margin: 0, fontSize: '1.05rem' }}>📁 Pick an image from your library</h3>
          <button type="button" onClick={onClose} className="btn-ghost" style={{ padding: '4px 10px' }}>✕</button>
        </div>

        {/* Tabs */}
        <div style={{ display: 'flex', gap: 4, borderBottom: '1px solid var(--border, rgba(99,102,241,0.15))' }}>
          <button
            type="button"
            onClick={() => setTab('uploads')}
            style={{
              padding: '8px 16px',
              background: 'transparent',
              border: 'none',
              borderBottom: tab === 'uploads' ? '2px solid var(--accent-cyan)' : '2px solid transparent',
              color: tab === 'uploads' ? 'var(--text)' : 'var(--text-muted)',
              fontWeight: tab === 'uploads' ? 600 : 400,
              cursor: 'pointer',
              fontSize: '0.9rem',
            }}
          >
            📁 Uploads <span style={{ fontSize: '0.78rem', color: 'var(--text-dim)' }}>({uploads?.length ?? '…'})</span>
          </button>
          <button
            type="button"
            onClick={() => setTab('gallery')}
            style={{
              padding: '8px 16px',
              background: 'transparent',
              border: 'none',
              borderBottom: tab === 'gallery' ? '2px solid var(--accent-cyan)' : '2px solid transparent',
              color: tab === 'gallery' ? 'var(--text)' : 'var(--text-muted)',
              fontWeight: tab === 'gallery' ? 600 : 400,
              cursor: 'pointer',
              fontSize: '0.9rem',
            }}
          >
            🖼️ Gallery <span style={{ fontSize: '0.78rem', color: 'var(--text-dim)' }}>({gallery?.length ?? '…'})</span>
          </button>
        </div>

        {/* Search */}
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder={tab === 'uploads' ? 'Search by filename…' : 'Search by tool name or prompt…'}
          style={{ width: '100%', fontSize: '0.9rem' }}
        />

        {error && <div style={{ color: 'var(--error)', fontSize: '0.85rem' }}>{error}</div>}

        {/* Content */}
        <div style={{
          overflowY: 'auto' as const,
          maxHeight: 'calc(90vh - 220px)',
          minHeight: 240,
        }}>
          {tab === 'uploads' ? (
            loadingUploads ? (
              <div style={{ padding: 40, textAlign: 'center' as const, color: 'var(--text-muted)' }}>Loading uploads…</div>
            ) : !filteredUploads || filteredUploads.length === 0 ? (
              <div style={{ padding: 40, textAlign: 'center' as const, color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                {uploads && uploads.length === 0
                  ? 'No uploads yet. Use "Choose Image" to upload one first.'
                  : 'No uploads match your search.'}
              </div>
            ) : (
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))',
                gap: 10,
              }}>
                {filteredUploads.map(u => (
                  <button
                    key={u.id}
                    type="button"
                    onClick={() => handlePickUpload(u)}
                    style={{
                      padding: 0,
                      background: 'rgba(0,0,0,0.2)',
                      border: '1px solid var(--border, rgba(99,102,241,0.12))',
                      borderRadius: 8,
                      cursor: 'pointer',
                      overflow: 'hidden',
                      textAlign: 'left' as const,
                      transition: 'transform 0.1s, border-color 0.1s',
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.borderColor = 'var(--accent-cyan)';
                      e.currentTarget.style.transform = 'translateY(-2px)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.borderColor = 'var(--border, rgba(99,102,241,0.12))';
                      e.currentTarget.style.transform = 'translateY(0)';
                    }}
                    title={u.originalName}
                  >
                    <div style={{ width: '100%', height: 110, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>
                      <img
                        src={u.imgbbThumbnailUrl || u.imgbbUrl || `/api/uploads/${u.id}/file`}
                        alt={u.originalName}
                        style={{ width: '100%', height: '100%', objectFit: 'cover' as const }}
                        loading="lazy"
                        onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }}
                      />
                    </div>
                    <div style={{ padding: '6px 8px', fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                      <div style={{ whiteSpace: 'nowrap' as const, overflow: 'hidden', textOverflow: 'ellipsis', color: 'var(--text)' }}>{u.originalName}</div>
                      <div style={{ marginTop: 2 }}>{(u.fileSize / 1024).toFixed(0)} KB · {new Date(u.createdAt).toLocaleDateString()}</div>
                    </div>
                  </button>
                ))}
              </div>
            )
          ) : (
            loadingGallery ? (
              <div style={{ padding: 40, textAlign: 'center' as const, color: 'var(--text-muted)' }}>Loading gallery…</div>
            ) : !filteredGallery || filteredGallery.length === 0 ? (
              <div style={{ padding: 40, textAlign: 'center' as const, color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                {gallery && gallery.length === 0
                  ? 'Gallery is empty. Run a webapp first to populate it.'
                  : 'No gallery items match your search.'}
              </div>
            ) : (
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fill, minmax(140px, 1fr))',
                gap: 10,
              }}>
                {filteredGallery.map(g => (
                  <button
                    key={g.id}
                    type="button"
                    onClick={() => handlePickGallery(g)}
                    style={{
                      padding: 0,
                      background: 'rgba(0,0,0,0.2)',
                      border: '1px solid var(--border, rgba(99,102,241,0.12))',
                      borderRadius: 8,
                      cursor: 'pointer',
                      overflow: 'hidden',
                      textAlign: 'left' as const,
                      transition: 'transform 0.1s, border-color 0.1s',
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.borderColor = 'var(--accent-cyan)';
                      e.currentTarget.style.transform = 'translateY(-2px)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.borderColor = 'var(--border, rgba(99,102,241,0.12))';
                      e.currentTarget.style.transform = 'translateY(0)';
                    }}
                    title={`${g.toolName}${g.prompt ? ` — ${g.prompt.slice(0, 80)}` : ''}`}
                  >
                    <div style={{ width: '100%', height: 110, background: 'rgba(0,0,0,0.4)', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>
                      <img
                        src={g.fileName?.startsWith('http') ? g.fileName : `/api/gallery/files/${g.id}`}
                        alt={g.toolName}
                        style={{ width: '100%', height: '100%', objectFit: 'cover' as const }}
                        loading="lazy"
                        onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }}
                      />
                    </div>
                    <div style={{ padding: '6px 8px', fontSize: '0.72rem', color: 'var(--text-muted)' }}>
                      <div style={{ whiteSpace: 'nowrap' as const, overflow: 'hidden', textOverflow: 'ellipsis', color: 'var(--text)' }}>
                        {g.toolName} <span style={{ color: 'var(--accent-cyan)', fontWeight: 600 }}>· result</span>
                      </div>
                      {g.prompt && (
                        <div style={{ marginTop: 2, whiteSpace: 'nowrap' as const, overflow: 'hidden', textOverflow: 'ellipsis' }}>
                          {g.prompt.slice(0, 40)}{g.prompt.length > 40 ? '…' : ''}
                        </div>
                      )}
                      <div style={{ marginTop: 2 }}>{new Date(g.createdAt).toLocaleDateString()}</div>
                    </div>
                  </button>
                ))}
              </div>
            )
          )}
        </div>
      </div>
    </div>
  );
}
